site_name: Spaghetti Coding Gods
site_url: https://robertvandecamp.github.io/spaghetti-gods/
theme:
  name: material
  font:
    text: Roboto             # Main text font
    code: Roboto Mono        # Code block font
  icon:
    logo: fontawesome/solid/computer

  # Enable light/dark mode toggle
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom         # Primary color for headers, nav, etc
      accent: custom          # Accent color for buttons, links, etc
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom         # Primary color for headers, nav, etc
      accent: custom          # Accent color for buttons, links, etc
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.footer

# Markdown extensions for enhanced content
markdown_extensions:
  - attr_list               # Enables custom HTML attributes
  - md_in_html             # Allows Markdown inside HTML blocks
  - pymdownx.emoji:        # Enables emoji and icon support
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences   # Enhanced code and content blocks
  - pymdownx.tabbed:       # Enables content tabs
      alternate_style: true 
  - admonition            # Enables callout blocks
  - pymdownx.details      # Enables collapsible blocks


  # Custom color definitions
extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Robert van de Camp.

nav:
  - Home: index.md
  - Page 1: page-1.md
  - Page 2: page-2.md
  - Page 3: page-3.md
  - Page 4: page-4.md
  - Page 5: page-5.md
  - Page 6: page-6.md
  - Page 7: page-7.md
  - Page 8: page-8.md
  - Page 9: page-9.md
  - Page 10: page-10.md
  - Page 11: page-11.md